### ISSUE TITLE
Reuse of Contact Point

### ISSUE THREAD

**Issue by maximepittomvils** [catalogue-of-services-isa/SDG-search-service-model#41]
**Concept**
Contact Point

**Description**
How to reuse existing models defining Contact Point? 

**Proposition**
We propose to align with CPSV-AP and CPOV. In the current revision of CPOV, the reuse of schema.org:ContactPoint is questioned. Depending on the outcome of the discussions and the revision of CPOV, this model could be updated. https://semiceu.github.io/CPOV/releases/2.00/

**Comment by vintra73** [comment]
see the considerations reported in #42

**Comment by maximepittomvils** [comment]
Based on the discussion during the third webinar on the model, we have decided to remove Contact Point from the model. The reasoning behind is that the information is too detailed at this stage.
