### ISSUE TITLE
Need for additional channels

### ISSUE THREAD

**Issue by maximepittomvils** [catalogue-of-services-isa/SDG-search-service-model#43]
**Concept**
Webpage

**Description**
In addition to Webpage, is there a need for additional channels through which you can initiate the Public Service?  (e.g. online enquiry form)

**Proposition**
In CPSV-AP, the class Channel captures the different media through which an Agent provides, uses or interacts in another way with a Public Service. It can be added to the model and the Webpage as well as other types of Channels could be described more specifically as subclasses of it. 

Is there a need to have additional channels?

**Comment by anarosa-es** [comment]
I think that this information should be kept in the webpage because this is information likely to change

**Comment by maximepittomvils** [comment]
By having Webpage, we have 1 specific kind of Channel. For the use case we are discussing today, that is probably the only thing we need now. The further complexity of capturing other types of Channels, should be left at national/regional/local level.
