### ISSUE TITLE
Define the content of the Webpage

### ISSUE THREAD

**Issue by maximepittomvils** [catalogue-of-services-isa/SDG-search-service-model#44]
**Concept**
Webpage

**Description**
Should we capture the kind of page the URL of the class Webpage will point to? For example, if there are multiple pages, e.g. one with information and one to request the service, do we want to specify the distinction explicitly?

**Proposition**
We could add a type property to include information about the kind of content the Webpage is providing.

**Comment by anarosa-es** [comment]
Yes. Currenty we have two types of SDG links: information (general rules) and procedure (info on a procedure), but I also see useful to add third type "application" (or something similar). 
However, one webpage can be of multiple types

**Comment by maximepittomvils** [comment]
We agreed to capture the type of the URL. We should bear in mind that what we display as results should be short. Keeping the two types of the implementing act would be sufficient (Information, Procedure). Additionally, to be decided to include a property which identifies whether or not a procedure is provided online or not.

**Comment by maximepittomvils** [comment]
We decided to keep the two types as sufficient (information/procedure).

**Comment by anarosa-es** [comment]
I am just curious, why "type" of webpage is optional in model 1.0? What case is trying to cover this optionality?
