### ISSUE TITLE
Multiplicity of the webpages for one service

### ISSUE THREAD

**Issue by maximepittomvils** [catalogue-of-services-isa/SDG-search-service-model#45]
**Concept**
has webpage (relationship between Public Service and Webpage)

**Description**
Should we allow several pages to be indicated per service or only one?

**Proposition**
This depends on the decision taken on the issue #44 .

At this moment in time, we have allowed the possibility to indicate several Webpages per Public Service. From a user perspective, this would give us the ability to provide the choice of the page to the reader.

**Comment by anarosa-es** [comment]
Usually, there is one web page per language (different URL per language)

**Comment by vintra73** [comment]
as indicated the proposal is linked to 44, the proposal indicated to 44 is preferred: an untyped list of endpoints increases the entropy of the end user

**Comment by maximepittomvils** [comment]
We decided to keep the cardinality 1..*, so that Member States are free to choose how much webpages they indicate.
